name: build linux
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make clang-12 the default
        run: sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-12 100

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: "3.26.x"

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch --move-include

      - name: move deps
        run: |
          mkdir temp
          mv deps/include temp/
          mv deps temp/src

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        working-directory: src

      - name: build
        run: cmake --build . --clean-first
        working-directory: src

      - uses: actions/upload-artifact@v2
        with:
          name: nimble Linux Library
          path: |
            src/libnimble.a
