name: Build MacOS Ventura
on: [push]
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.25.x'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch -t src/deps

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        working-directory: src

      - name: build
        run: cmake --build . --clean-first
        working-directory: src

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Nimble MacOS Framework
          path: |
            src/lib/libnimble.a
            src/CMakeLists.txt
