name: Build MacOS Ventura
on: [push]
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.25.x'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch --move-include

      - name: move deps
        run: |
          mkdir temp
          mv deps/include temp/
          mv deps temp/src
          find temp/src -depth -type d \( -name "examples" -o -name "example" -o -name "test" -o -name "tests" -o -name ".github" \) -exec rm -rf {} \;
          cp src/CMakeLists.txt temp/

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        working-directory: temp

      - name: build
        run: cmake --build . --clean-first
        working-directory: temp

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Nimble MacOS Framework
          path: |
            temp/nimble.framework
            temp/CMakeLists.txt
